/*
 * =============================================================================
 *
 *       Filename: erorhandler.h
 *
 *    Description: Captures and processes all the error codes generated by the
 *                 Docketmaster program.
 *
 *        Version: 1.0
 *        Created: 03/11/2012 12:33:51 PM
 *  Last Modified: Sun 11 Mar 2012 01:01:54 PM PDT
 *       Compiler: gcc
 *
 *         Author: Thomas H. Vidal (THV), thomasvidal@hotmail.com
 *   Organization: Dark Matter Software
 *
 *      Copyright: Copyright (c) 2012, Thomas H. Vidal
 *
 *	        Usage: Used by DocketMaster
 *    File Format: 
 *   Restrictions: 
 * Error Handling: Presently, most of the error conditions ungracefully exit the
 *                 application.  Currently, the module just collects all the
 *                 errors.  At a later point, a more robust exception handling
 *                 mechanism will be implemented with one goal: to recover from
 *                 problems so that the program will continue to run and
 *                 produce accurate output.
 *     References: 
 *          Notes: 
 * =============================================================================
 */

#ifndef _ERRORHANDLER_H_INCLUDED_
#define _ERRORHANDLER_H_INCLUDED_


/* #####   HEADER FILE INCLUDES   ########################################### */

/* #####   EXPORTED MACROS   ################################################ */

/* #####   EXPORTED SYMBOLIC CONSTANTS   #################################### */

/*------------------------------------------------------------------------------
 *  Macro definitions for error codes.
 *----------------------------------------------------------------------------*/
#define NOERROR 0
#define BADCOMMANDLINE 1
#define NULSTRING 2
#define NOFDELIM 3
#define NOTDELIM 4



/* #####   EXPORTED TYPE DEFINITIONS   ###################################### */

/* #####   EXPORTED DATA TYPES   ############################################ */

/* #####   EXPORTED VARIABLES   ############################################# */

/* #####   EXPORTED FUNCTION DECLARATIONS   ################################# */

void usage(char *);
void errorprocessor(int errcode);


#endif	/* _ERRORHANDLER_H_INCLUDED_ */
